version: '3'

services:
  fastapi:
    build: ./fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5010

  mlflow:
    build: ./mlflow
    ports:
      - "5010:5010"
    volumes:
      - ./mlflow:/mlflow
      - mlflow_data:/mlflow/data
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5010

  jupyter:
    build: ./jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter:/jupyter
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5010

volumes:
  mlflow_data: 